config/routes.rb
Rails.application.routes.draw do



  # devise_for :admins, skip: :all
  # devise_scope :admin do
  #   get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
  #   post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
  #   delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  # end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  #devise_for :customers, skip: :all
  #devise_scope :customer do
   # get 'customers/:id/password/new' => 'customers/passwords#new', as: 'new_customer_password'
    #get 'customers/:id/password/edit' => 'customers/passwords#edit', as: 'edit_customer_password'
    #post 'customers/:id/password/edit' => 'customers/passwords#update'
    #get 'customers/password/new' => 'customers/passwords#new'
  #end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  'admin' => 'admin/homes#top'
  namespace :admin do
  	resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
	end

  # get  'items' => 'customer/items#index', as: "customer_items"
  # get  'items/:id' => 'customer/items#show', as: "customer_item"
  # resources :cart_items, only:[:create, :index, :update, :destroy] do
  #   collection do
  #     delete 'destroy_all'
  #   end
  # end

  #get "admin/orders/:id" => "admin/orders#show", as: "admin_order"
  #patch "admin/orders/:id" => "admin/orders#update"
  # get '/search' => 'search#search'



#  get "orders/new" => "public/orders#new"
#  get "orders/confirm" => "public/orders#confirm"
#  post "orders/confirm" => "public/orders#create"
#  get "thanks" => "public/orders#thanks"
#  get "orders", to: "/public/orders#index", as: "customer_orders"
#  get "orders/:id", to: "public/orders#show", as: "customer_order"
  get 'about', to: 'public/homes#about', as: "about"
#  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"

  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"


  scope module: 'public' do
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
     get 'genres/:id/search' => 'searches#genre_search'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
        root 'homes#top'
        get "about" => "homes#about"

       resources :items, only:[:index, :show]
        resources :cart_items, only:[:create, :index, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
      # get 'genres/:id/search' => 'searches#genre_search'
      get '/customers/my_page', to: '/public/customers#show', as: 'customer_my_page'
      get '/customers/information/edit', to: '/public/customers#edit', as: 'edit_customer', format: false
      patch '/customers/information', to: '/public/customers#update', as: 'information'
      get '/customers/quit', to: 'customers#quit', as: 'quit'
      get '/customers/unsubscribe', to: '/public/customers#unsubscribe', as: 'unsubscribe_customer'
      patch '/customers/withdraw', to: '/public/customers#withdraw', as: 'withdraw_customer'







     # resources :customers do
      #member do
      #  patch :withdraw
      #  get :unsubscribe
      #end
      #end

      resources :'mailing_addresses', only:[:index, :create, :edit, :update, :destroy]
    end
   end

  #scope module: :public do
    #post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]resources :orders, only: [:new, :create, :index, :show]
  #end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 validates :address, presence: true
  has_many :cart_items
  has_many :orders

  def addresses

    postal_code + address + first_name + last_name

  end

 # def active_for_authentication?
  #  super && (is_active == true)
  #end
end

app/controllers/admin/customers_controller.rb
 class Admin::CustomersController < ApplicationController
   before_action :authenticate_admin!

  def index
   @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
   @customer = Customer.find(params[:id])
  end

  def edit
   @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   @customer.update(customer_params)
   redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

 end

app/views/admin/customers/edit.html.erb
<div class='container'>
 <div class='row'>
  <div class='col-md-12'>

  <div class='row'>
   <div class='col-5 text-center'>
    <h3 class="table-active"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h3>
    </div>
  <div class='col-7'></div>
  </div>

  <div class="mb-4"></div>

   <div class='row'>
      <div class='col-3'><h4>会員ID</h4></div>
      <div class='col-3'><h4><%= @customer.id %></h4></div>
      <div class='col-6'></h4></div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path do |customer| %>
   <%= render "public/shared/error_messages", resource: @customer %>
  <div class='row'>
    <div class='col-3'><h4><%= customer.label :first_name, "氏名" %></h4></div>
    <div class='col-3'><h4><%= customer.text_field :first_name, style: "width: 90%" %></h4></div>
    <div class='col-3'><h4><%= customer.text_field :last_name, style: "width: 90%" %></h4></div>
    <div class='col-3'><h4></h4></div>
  </div>

  <div class='row'>
    <div class='col-3'><h4><%= customer.label :first_name_kana, "フリガナ" %></h4></div>
    <div class='col-3'><h4><%= customer.text_field :first_name_kana, style: "width: 90%" %></h4></div>
    <div class='col-3'><h4><%= customer.text_field :last_name_kana, style: "width: 90%" %></h4></div>
    <div class='col-3'><h4></h4></div>
  </div>


  <div class='row'>
    <div class='col-3'><h4><%= customer.label :postal_code, "郵便番号" %></h4></div>
    <div class='col-3'><h4><%= customer.text_field :postal_code, style: "width: 90%" %></h4></div>
    <div class='col-6'><h4></h4></div>
  </div>

  <div class='row'>
    <div class='col-3'><h4><%= customer.label :address, "住所" %></h4></div>
    <div class='col-9'><h4><%= customer.text_field :address, style: "width: 90%" %></h4></div>
  </div>

   <div class='row'>
   <div class='col-3'><h4><%= customer.label :telephone_number, "電話番号" %></h4></div>
   <div class='col-3'><h4><%= customer.text_field :telephone_number, style: "width: 90%" %></h4></div>
   <div class='col-6'><h4></h4></div>
  </div>

  <div class='row'>
    <div class='col-3'><h4><%= customer.label :email, "メールアドレス" %></h4></div>
    <div class='col-3'><h4><%= customer.email_field :email, autofocus: true, autocomplete: "email", style: "width: 90%" %></h4></div>
    <div class='col-6'><h4></h4></div>
  </div>

  <div class='row'>
   <div class='col-3'><h4>会員ステータス</h4></div>
   <div class='col-1'><h4><%= customer.radio_button :is_active, "true" %>有効</h4></div>
   <div class='col-1'><h4><%= customer.radio_button :is_active, "false" %>退会</h4></div>
   <div class='col-7'></div>
  </div>

 <div class="mb-5"></div>

  <div class='row'>
  <div class='col-3'></div>
  <div class="col-md-3">
   <div class="actions">
    <h4><%= customer.submit "変更を保存", class: 'btn btn-success btn-lg', style: "width: 80%" %></h4>
   </div>
   <div class='col-6'></div>
  </div>
  </div>
  <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>

    <div class="mb-3"></div>

    <div class='row'><h4 class="table-active">会員一覧</h4></div>
    <div class="mb-md-3"></div>
 <table class="table table-hover table-inverse">

    <div class='row'>
     <thead class="thead-light">
     <tr>
     <th class='col-md-2'>会員ID</th>
     <th class='col-md-3'>氏名</th>
     <th class='col-md-3'>メールアドレス</th>
     <th class='col-md-3'>ステータス</th>
     </tr>
     </thead>
    </div>



 <div class='row'>
   <tbody class="text-left">
     <% @customers.each do |customer| %>
    <tr>
     <td><%= customer.id %></td>
     <td><%= link_to admin_customer_path(customer.id) do %>
       <%= customer.first_name %><%= customer.last_name %>
      <% end %>
     </td>
     <td><%= customer.email %></td>
     <td class="<%= customer.is_active ? 'text-success' : '' %>">
      <%= customer.is_active ? "有効" : "退会" %>
      </td>
      </tr>
      <% end %>
     </tbody>
 </div>
 </table>
 <div class='row text-center'>
  <div class='col-md-3'></div>
  <div class='col-md-6'>
   <%= paginate @customers %></div>
  <div class='col-md-3'></div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
<table class="table table-borderless">

  <div class='row'>
  <div class='col-md-5'>
  <h3 class="table-active"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細 </h3>
    <div class='col-md-7'></div>
  </div>

   <div class='row'>
    <th class='col-md-3 text-left'>会員ID</th>
    <td class='col-md-9 text-left'><%= @customer.id %></td>
   </div>

    <tr class="text-left">
     <th>氏名</th>
     <td><%= @customer.first_name %> <%= @customer.last_name %></td>
    </tr>

    <tr class="text-left">
      <th>フリガナ</th>
      <td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
    </tr>

    <tr class="text-left">
     <th>郵便番号</th>
     <td><%= @customer.postal_code %></td>
    </tr>

    <tr class="text-left">
     <th>住所</th>
     <td><%= @customer.address %></td>
    </tr>

    <tr class="text-left">
     <th>電話番号</th>
     <td><%= @customer.telephone_number %></td>
    </tr>

    <tr class="text-left">
     <th>メールアドレス</th>
     <td><%= @customer.email %></td>
    </tr>

    <tr class="text-left">
     <th>会員ステータス</th>
     <td class="<%= @customer.is_active ? 'text-success' : '' %>">
      <%= @customer.is_active ? "有効" : "無効" %>
     </td>
    </tr>

   <tr>
    <td>
      <%= link_to edit_admin_customer_path(@customer), class: "btn btn-success btn-lg" do %>
      <i>編集する</i>
      <% end %>
    </td>
   <td>
      <%= link_to admin_path, class: "btn btn-primary btn-lg" do %>
     <i>注文履歴一覧を見る</i>
      <% end %>
    </td>
  </tr>
   </div>
 </div>
 </table>
</div>