config/routes.rb
Rails.application.routes.draw do



  # devise_for :admins, skip: :all
  # devise_scope :admin do
  #   get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
  #   post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
  #   delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  # end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  #devise_for :customers, skip: :all
  #devise_scope :customer do
   # get 'customers/:id/password/new' => 'customers/passwords#new', as: 'new_customer_password'
    #get 'customers/:id/password/edit' => 'customers/passwords#edit', as: 'edit_customer_password'
    #post 'customers/:id/password/edit' => 'customers/passwords#update'
    #get 'customers/password/new' => 'customers/passwords#new'
  #end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  'admin' => 'admin/homes#top'
  namespace :admin do
  	resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
	end

  # get  'items' => 'customer/items#index', as: "customer_items"
  # get  'items/:id' => 'customer/items#show', as: "customer_item"
  # resources :cart_items, only:[:create, :index, :update, :destroy] do
  #   collection do
  #     delete 'destroy_all'
  #   end
  # end

  #get "admin/orders/:id" => "admin/orders#show", as: "admin_order"
  #patch "admin/orders/:id" => "admin/orders#update"
  # get '/search' => 'search#search'



#  get "orders/new" => "public/orders#new"
#  get "orders/confirm" => "public/orders#confirm"
#  post "orders/confirm" => "public/orders#create"
#  get "thanks" => "public/orders#thanks"
#  get "orders", to: "/public/orders#index", as: "customer_orders"
#  get "orders/:id", to: "public/orders#show", as: "customer_order"
  get 'about', to: 'public/homes#about', as: "about"
#  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"

  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"


  scope module: 'public' do
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
     get 'genres/:id/search' => 'searches#genre_search'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
        root 'homes#top'
        get "about" => "homes#about"

       resources :items, only:[:index, :show]
        resources :cart_items, only:[:create, :index, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
      # get 'genres/:id/search' => 'searches#genre_search'
      get '/customers/my_page', to: '/public/customers#show', as: 'customer_my_page'
      get '/customers/information/edit', to: '/public/customers#edit', as: 'edit_customer', format: false
      patch '/customers/information', to: '/public/customers#update', as: 'information'
      get '/customers/quit', to: 'customers#quit', as: 'quit'
      get '/customers/unsubscribe', to: '/public/customers#unsubscribe', as: 'unsubscribe_customer'
      patch '/customers/withdraw', to: '/public/customers#withdraw', as: 'withdraw_customer'







     # resources :customers do
      #member do
      #  patch :withdraw
      #  get :unsubscribe
      #end
      #end

      resources :'mailing_addresses', only:[:index, :create, :edit, :update, :destroy]
    end
   end

  #scope module: :public do
    #post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]resources :orders, only: [:new, :create, :index, :show]
  #end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  validates :address, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: {
    wait_payment: 0,
    confirm_payment: 1,
    making: 2,
    preparing_ship: 3,
    finish_prepare: 4

  }
end

app/controllers/admin/order_controller.rb
class Admin::OrderController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    # # @total_price = 0
    # # @order_details.each do |order_detail|
    # #   @total_price += (order_detail.item.price * 1.1 * order_detail.amount).floor
    # end
  end

  def update
    order = Order.find(params[:id])
    order_details = order.order_details
    order.update(order_params)

    if order.status == "confirm_payment"
      order_details.update_all(making_status: "waiting_manufacture")
    end
		redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    # # @total_price = 0
    # # @order_details.each do |order_detail|
    # #   @total_price += (order_detail.item.price * 1.1 * order_detail.amount).floor
    # end
  end

  def update
    order = Order.find(params[:id])
    order_details = order.order_details
    order.update(order_params)

    if order.status == "confirm_payment"
      order_details.update_all(making_status: "waiting_manufacture")
    end
		redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <label class="h4 bg-light px-4">注文履歴詳細</label>
  <div class="row mb-2">

    <div class="col-lg-6">
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td><%= link_to (@order.customer.first_name + ' ' + @order.customer.last_name), admin_customer_path(@order.customer.id) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url:admin_order_path(@order), method: :patch do |order| %>
              <%= order.select :status, Order.statuses_i18n.invert %>
              <%= order.submit '更新', class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>

  </div>

  <div class="row mb-2">

    <div class="col-lg-8">
      <table class="table table shadow-sm">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
        <% @order_details.each do |order_detail| %>
        <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price * 1.1).floor.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= ((order_detail.item.price * 1.1) * order_detail.amount).floor.to_s(:delimited) %></td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |makes| %>
            <td><%= makes.select :making_status, OrderDetail.making_statuses_i18n.invert %></td>
            <td><%= makes.submit '更新', class:"btn btn-success" %></td>
          <% end %> <!-- form_withタグの閉じタグを追加 -->
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 offset-8 d-flex align-items-end mb-2">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= number_to_currency(@order.total_payment - @order.shipping_cost, unit: '', precision: 0) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= number_to_currency(@order.shipping_cost, unit: '', precision: 0) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= number_to_currency(@order.total_payment, unit: '', precision: 0) %>円</td>
        </tr>
      </table>
    </div>

  </div>
</div>