config/routes.rb
Rails.application.routes.draw do



  # devise_for :admins, skip: :all
  # devise_scope :admin do
  #   get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
  #   post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
  #   delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
  # end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  #devise_for :customers, skip: :all
  #devise_scope :customer do
   # get 'customers/:id/password/new' => 'customers/passwords#new', as: 'new_customer_password'
    #get 'customers/:id/password/edit' => 'customers/passwords#edit', as: 'edit_customer_password'
    #post 'customers/:id/password/edit' => 'customers/passwords#update'
    #get 'customers/password/new' => 'customers/passwords#new'
  #end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  'admin' => 'admin/homes#top'
  namespace :admin do
  	resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
	end

  # get  'items' => 'customer/items#index', as: "customer_items"
  # get  'items/:id' => 'customer/items#show', as: "customer_item"
  # resources :cart_items, only:[:create, :index, :update, :destroy] do
  #   collection do
  #     delete 'destroy_all'
  #   end
  # end

  #get "admin/orders/:id" => "admin/orders#show", as: "admin_order"
  #patch "admin/orders/:id" => "admin/orders#update"
  # get '/search' => 'search#search'



#  get "orders/new" => "public/orders#new"
#  get "orders/confirm" => "public/orders#confirm"
#  post "orders/confirm" => "public/orders#create"
#  get "thanks" => "public/orders#thanks"
#  get "orders", to: "/public/orders#index", as: "customer_orders"
#  get "orders/:id", to: "public/orders#show", as: "customer_order"
  get 'about', to: 'public/homes#about', as: "about"
#  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"

  patch "customers/:id/quit" => "customer/customers#invalid", as: "invalid_customer"


  scope module: 'public' do
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
     get 'genres/:id/search' => 'searches#genre_search'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
        root 'homes#top'
        get "about" => "homes#about"

       resources :items, only:[:index, :show]
        resources :cart_items, only:[:create, :index, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
      # get 'genres/:id/search' => 'searches#genre_search'
      get '/customers/my_page', to: '/public/customers#show', as: 'customer_my_page'
      get '/customers/information/edit', to: '/public/customers#edit', as: 'edit_customer', format: false
      patch '/customers/information', to: '/public/customers#update', as: 'information'
      get '/customers/quit', to: 'customers#quit', as: 'quit'
      get '/customers/unsubscribe', to: '/public/customers#unsubscribe', as: 'unsubscribe_customer'
      patch '/customers/withdraw', to: '/public/customers#withdraw', as: 'withdraw_customer'







     # resources :customers do
      #member do
      #  patch :withdraw
      #  get :unsubscribe
      #end
      #end

      resources :'mailing_addresses', only:[:index, :create, :edit, :update, :destroy]
    end
   end

  #scope module: :public do
    #post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]post "orders/confirm" => "orders#confirm"
    #get "orders/thanks" => "orders#thanks"
    #resources :orders, only: [:new, :create, :index, :show]resources :orders, only: [:new, :create, :index, :show]
  #end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a6ec9f15fd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm border-bottom border-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
            <%= image_tag 'logo1.png', size: '150x100', class: 'img-fluid' %>
          </a>
          <div class="mt-3">
            <% if customer_signed_in? %>
              <p>ようこそ<%= current_customer.last_name %>さん！</p>
            <% end %>
          </div>

          <div class="col text-right">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="ml-auto">
              <ul class="navbar-nav">
              <% if customer_signed_in? %>
                <li class="navbar-link my-1 ml-1"><%= link_to "マイページ", customer_my_page_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %></li>

              <% elsif admin_signed_in? %>
                <li class="navbar-link my-1 ml-1"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
              <% else %>
                <li class="navbar-link my-1 ml-1"><%= link_to "About", about_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %></li>
                <li class="navbar-link my-1 ml-1"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <!--<p id="notice"><%#= notice %></p>-->
      <%= yield %>
    </main>

    <footer class="border border-dark fixed-bottom pt-5 pb-4">
    </footer>
  </body>
</html>